language: node_js

node_js:
  - node
  - 14
  - 13
  - 12
  - 11

before_script:
  - npm run install:dev

script:
  - node --version
  - npm --version
  - npm run test:codecov
  - npm run test:coveralls

cache:
  npm: true
  packages: true

os:
  - windows

arch: arm64

jobs:
  fast_finish: true
