clone_depth: 50

image:
  - Visual Studio 2019
  - Ubuntu

environment:
 matrix:
 - nodejs_version: "14"
 - nodejs_version: "13"
 - nodejs_version: "12"
 - nodejs_version: "11"

install:
- ps: Install-Product node $env:nodejs_version

before_test:
- npm run install:dev

test_script:
- node --version
- npm --version
- npm run test:codecov
- npm run test:coveralls

cache:
- node_modules

os: 
  - Windows Server 2019
  - Ubuntu 16.04.6 LTS (Xenial Xerus)

build: off

matrix:
 fast_finish: true