codecov:
      token: ""
      require_ci_to_pass: yes
      bot: "restuwahyu13"
      ci:
        - travis-ci.org
        - appveyor

coverage:
    round: up
    range: "80...100"

parsers:
    javascript:
      enable_partials: yes
